version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart:
      on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/warehouse?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root-user
      - SPRING_DATASOURCE_PASSWORD=root@123
    networks:
      - springmysql-net
  db:
    image: mysql:latest
    networks:
      - springmysql-net
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=warehouse
      - MYSQL_USER=root-user
      - MYSQL_PASSWORD=root@123
      - DATABASE_PORT=3306
    volumes:
      - ./data:/var/lib/mysql
networks:
  springmysql-net:
